### PR TITLE
#30 Set Schedule

### LINKED ISSUE #30: US-30: As a monitoring user, I want to be able to set time - location schedule with arrival time interval, departure time interval and location address for every user on my supervised users list

### LINKED ISSUE #178: BUG-178: "fullName" variable being added to database which is unnecessary
### Related Issue(s): 
None

### Relevant File(s):
User.java

### Describe the bug:
The database would add a variable/field, fullName, in a User document when adding a user; this isn't intentional behaviour. 
This does not follow our ER diagram, and we store the firstName and lastName anyway.

### To Reproduce:
Steps to reproduce the behaviour:
1. Open App
2. Register as normal
3. fullName is added to the database

### Expected behaviour
The variable fullName is not added to the database.

### Screenshots:
image

### PR DESCRIPTION
**Pull request by refatK**
### Important Note (as of January 14)
Right now, github is updating their CI machines and its leading to build issues. As a result, Reviewdog builds will be failing for now. Here's a link explaining the issue if you are curious:
https://github.com/actions/virtual-environments/issues/2420

----

### Related Issues
#30, #178 (just a tiny bug fix)

### Description
Added a page where schedules can be added to selected members of a group.

### How to check PR

1. Login as a user with a group that has a couple of users (ex: bigowl123)
2. Click on SetSchedule button
3. Fill out the form
4. Click on Set Schedule Button to add the schedule

Result: You should return to the previous page and there should be a new schedule in the database in the schedules collection if Firestore

###  Important Files:

- SetScheduleActivity.java
- Schedule.java
- SetScheduleViewModel.java

### Images
image
image

### CODE REVIEW

**Comment by refatK** [comment]
There are some quality issues, so we'll try to fix them up.

**Comment by refatK** [comment]
We did a bunch of clean up and fixes. The other Sonar issues are too be fixed in another soon to be merged branch so no worries about those.

Ready to review!

**Review by KennanHoa — APPROVED** [review]
No issue running the app and the adding schedule function works flawlessly.
Code is clean and comprehensible. Good job!
Good Tests implementations

**Review by KhangZhengNg — APPROVED** [review]
Tested and worked well on both emulator and actual phone. Good tests  that cover many actions  on creating schedule

**Pull request merged**
