### PR TITLE
#58 data models

### PR DESCRIPTION
**Pull request by ShawnGuerra-Bautista**
Issues: #58

This branch will be pushed into the staging branch.

Tasks done:

- [X] Created models:
- User 
- Group

We also created the Schedule and Notification models, but those are not completed as they are just there as placeholders. The models' purpose is to make Java objects out of the database's data.

- [x] Created Repositories:
- Repository
- UserRepository
- GroupRepository

The repositories' purpose is to communicate with the database whether it would be fetching data, or uploading data.

**Note: The repository and model classes are going to progressively change as the project goes on. Also, TravisCI is not fully functional and will be fixed in another Pull-Request so please ignore it for now.**

Side note: We will be using the MVVM android architecture; it is important that we follow this architecture as it will make testing much easier. Don't worry, I will be helping you guys understand it; I will be creating another branch which will show an example on how to use the Repository classes, and how the MVVM architecture looks like. We wanted to fully implement an Activity that utilizes the Repositories and show the MVVM architecture, but it's not in the scope of #58 or this pull-request.

### CODE REVIEW

**Comment by darkheros12** [comment]
Please link all the issues into this PR.

**Comment by ShawnGuerra-Bautista** [comment]
All the issues are already linked which is issue #58.

**Comment by ShawnGuerra-Bautista** [comment]
@darkheros12 All the issues are already mentioned; it's in the title: issue #58. I'll put it on the description if it's not understandable.

**Review by darkheros12 — APPROVED** [review]
This PR has a big commit because it has the commit file from sign in/out and sign up previously. It is already in master. This is staging. as for the Travis CI, there is no test yet so CI can wait for later.

**Comment by ggebran** [comment]
Code is consistent and no runtime errors. Good job.

**Review by ggebran — APPROVED** [review]
All good here.

**Pull request merged**
