### PR TITLE
#50 welcome page and #58 data model for notification

### PR DESCRIPTION
**Pull request by ShawnGuerra-Bautista**
Issues: [#50, #58]

Tasks done:
- Create a splash screen for application [Related to issue #50]
  - Decoupled the MainActivity and the SignUp functionality
  - Added a Splash Screen Activity that lasts for 2 seconds

- Create data models for notifications [Related to issue #58]
  - To Help with #3, we added the notification related models and repositories.

### CODE REVIEW

**Review by Landry333 — APPROVED** [review]
Looks good to me

**Review by darkheros12 — APPROVED** [review]
it looks good to me

**Review by darkheros12 — CHANGES_REQUESTED** [review]
I think this should pull from staging before merging to staging

**Review by KhangZhengNg — CHANGES_REQUESTED** [review]
This cant be approved as we agreed to let previous PR #84 to be merged first.

**Review by refatK — CHANGES_REQUESTED** [review]
I tried it, and the splash screen works, but it looks a little stretched. You should make it so that the logo doesn't stretch based on the device screen size

image

**Review by refatK — APPROVED** [review]
The logo doesn't stretch anymore! Approved.

**Review by darkheros12 — APPROVED** [review]
I tested the code. The welcome page is nice. However, we should maybe extend the time required for the firebase to connect to the app. Maybe in a later issue. But for it is good enough.

**Pull request merged**
